export const rows = [
  {
    id: 1,
    name: "Mohamed Idrissi",
    email: "mohamedidrissi@gmail.com",
    age: 62,
    phone: "(+212)012345678",
    access: "Admin",
  },
  {
    id: 2,
    name: "Amina Idrissi",
    email: "aminaidrissi@gmail.com",
    age: 55,
    phone: "(+212)012345678",
    access: "Admin",
  },
  {
    id: 3,
    name: "Hamza Idrissi",
    email: "hamzaidrissi@gmail.com",
    age: 26,
    phone: "(+212)012345678",
    access: "Manager",
  },
  {
    id: 4,
    name: "Soufiane Idrissi",
    email: "soufiane idrissi@gmail.com",
    age: 23,
    phone: "(+212)012345678",
    access: "User",
  },
  {
    id: 5,
    name: "Salma Idrissi",
    email: "salmaidrissi@gmail.com",
    age: 19,
    phone: "(+212)012345678",
    access: "User",
  },
  {
    id: 6,
    name: "ALi Azkour",
    email: "aliazkour@gmail.com",
    age: 26,
    phone: "(+212)012345678",
    access: "User",
  },
];
